---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy1
  namespace: akila1456678
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 1
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: container
        image: akilag1997/app:7
        ports:
        - containerPort: 8080

---


apiVersion: v1
kind: Service
metadata:
  name: svc
  namespace: akila1456678
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: myapp
